In [6]:
import mysql.connector as sql
import pandas as pd
import numpy as mp 
import matplotlib.pyplot as plt

## Clean the Customers tabel

In [7]:
customers = pd.read_csv("C:\\Users\\hp\\OneDrive\\Desktop\\amazone\\customers.csv")
customers.head(5)

,customer_id,customer_name,email,phone,city,state,pincode,customer_segment,registration_date
0,10001,Customer_10001,customer10001@example.com,9634895718,Mumbai,Punjab,484096,Consumer,2023-01-18
1,10002,Customer_10002,customer10002@example.com,9299900595,Chennai,West Bengal,484096,Consumer,2022-01-17
2,10003,Customer_10003,customer10003@example.com,9962061404,Kochi,Delhi,484096,Consumer,2023-05-08
3,10004,Customer_10004,customer10004@example.com,9887846414,Ahmedabad,Haryana,484096,Home Office,2025-09-16
4,10005,Customer_10005,customer10005@example.com,9227521863,Gurugram,Rajasthan,484096,Consumer,2024-07-14

In [8]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 2510 entries, 0 to 2509
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2510 non-null   int64
 1   customer_name      2510 non-null   str
 2   email              2485 non-null   str
 3   phone              2510 non-null   int64
 4   city               2490 non-null   str
 5   state              2510 non-null   str
 6   pincode            2510 non-null   int64
 7   customer_segment   2510 non-null   str
 8   registration_date  2510 non-null   str
dtypes: int64(3), str(6)
memory usage: 176.6 KB

In [9]:
customers.isnull().sum()

customer_id           0
customer_name         0
email                25
phone                 0
city                 20
state                 0
pincode               0
customer_segment      0
registration_date     0
dtype: int64

In [10]:
customers.dropna(inplace=True)

In [11]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
city                 0
state                0
pincode              0
customer_segment     0
registration_date    0
dtype: int64

In [12]:
customers.duplicated().sum()

np.int64(10)

In [13]:
customers.drop_duplicates(inplace=True)

In [14]:
customers.duplicated().sum()

np.int64(0)

In [15]:
customers['city'].unique()

<StringArray>
[   'Mumbai',   'Chennai',     'Kochi', 'Ahmedabad',  'Gurugram', 'Hyderabad',
 'Bengaluru',  'Ludhiana',   'Lucknow',     'Delhi',   'Kolkata',    'Jaipur']
Length: 12, dtype: str

In [16]:
customers['state'].unique()

<StringArray>
[       'Punjab',   'West Bengal',         'Delhi',       'Haryana',
     'Rajasthan',     'Telangana',    'Tamil Nadu', 'Uttar Pradesh',
        'Kerala',       'Gujarat',   'Maharashtra',     'Karnataka']
Length: 12, dtype: str

In [17]:
customers['customer_segment'].unique()

<StringArray>
['Consumer', 'Home Office', 'Corporate']
Length: 3, dtype: str

In [18]:
customers.head(8)

,customer_id,customer_name,email,phone,city,state,pincode,customer_segment,registration_date
0,10001,Customer_10001,customer10001@example.com,9634895718,Mumbai,Punjab,484096,Consumer,2023-01-18
1,10002,Customer_10002,customer10002@example.com,9299900595,Chennai,West Bengal,484096,Consumer,2022-01-17
2,10003,Customer_10003,customer10003@example.com,9962061404,Kochi,Delhi,484096,Consumer,2023-05-08
3,10004,Customer_10004,customer10004@example.com,9887846414,Ahmedabad,Haryana,484096,Home Office,2025-09-16
4,10005,Customer_10005,customer10005@example.com,9227521863,Gurugram,Rajasthan,484096,Consumer,2024-07-14
5,10006,Customer_10006,customer10006@example.com,9523734972,Hyderabad,Telangana,484096,Corporate,2026-02-18
6,10007,Customer_10007,customer10007@example.com,9515968276,Kochi,Tamil Nadu,484096,Consumer,2025-11-30
7,10008,Customer_10008,customer10008@example.com,9770094950,Ahmedabad,Punjab,484096,Home Office,2022-04-27

## Clean the order_items table

In [19]:
order_items = pd.read_csv("C:\\Users\\hp\\OneDrive\\Desktop\\amazone\\order_items.csv")
order_items.head(5)

,order_item_id,order_id,product_id,quantity,discount_pct,gross_amount,discount_amount,net_amount
0,OI0000001,O003152,P0236,1,0,1113.12,0.00,1113.12
1,OI0000002,O009116,P0155,2,20,94514.76,18902.95,75611.81
2,OI0000003,O009422,P0295,4,10,185205.72,18520.57,166685.15
3,OI0000004,O004724,P0188,4,20,167241.68,33448.34,133793.34
4,OI0000005,O009193,P0209,4,0,38253.80,0.00,38253.80

In [20]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    15000 non-null  str
 1   order_id         15000 non-null  str
 2   product_id       15000 non-null  str
 3   quantity         15000 non-null  int64
 4   discount_pct     15000 non-null  int64
 5   gross_amount     15000 non-null  float64
 6   discount_amount  15000 non-null  float64
 7   net_amount       15000 non-null  float64
dtypes: float64(3), int64(2), str(3)
memory usage: 937.6 KB

In [21]:
order_items.isnull().sum()

order_item_id      0
order_id           0
product_id         0
quantity           0
discount_pct       0
gross_amount       0
discount_amount    0
net_amount         0
dtype: int64

In [22]:
order_items.duplicated().sum()

np.int64(0)

In [23]:
order_items.head(8)

,order_item_id,order_id,product_id,quantity,discount_pct,gross_amount,discount_amount,net_amount
0,OI0000001,O003152,P0236,1,0,1113.12,0.00,1113.12
1,OI0000002,O009116,P0155,2,20,94514.76,18902.95,75611.81
2,OI0000003,O009422,P0295,4,10,185205.72,18520.57,166685.15
3,OI0000004,O004724,P0188,4,20,167241.68,33448.34,133793.34
4,OI0000005,O009193,P0209,4,0,38253.80,0.00,38253.80
5,OI0000006,O007567,P0073,2,0,38260.96,0.00,38260.96
6,OI0000007,O009433,P0096,4,5,69144.60,3457.23,65687.37
7,OI0000008,O008648,P0011,3,0,11932.23,0.00,11932.23

## clean the orders table

In [24]:
orders = pd.read_csv("C:\\Users\\hp\\OneDrive\\Desktop\\amazone\\orders.csv")
orders.head(5)

,order_id,customer_id,order_date,order_status,payment_method,shipping_city,shipping_state
0,O000001,11824,2024-05-27,Delivered,Net Banking,Ludhiana,West Bengal
1,O000002,12012,2024-12-07,Delivered,Debit Card,Mumbai,Uttar Pradesh
2,O000003,12000,2025-05-09,Delivered,UPI,Ahmedabad,Karnataka
3,O000004,10411,2024-01-23,Delivered,COD,Delhi,Rajasthan
4,O000005,12293,2024-04-14,Delivered,Debit Card,Jaipur,Kerala

In [25]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 10020 entries, 0 to 10019
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10020 non-null  str
 1   customer_id     10020 non-null  int64
 2   order_date      10020 non-null  str
 3   order_status    10020 non-null  str
 4   payment_method  10005 non-null  str
 5   shipping_city   9990 non-null   str
 6   shipping_state  10020 non-null  str
dtypes: int64(1), str(6)
memory usage: 548.1 KB

In [26]:
orders.isnull().sum()

order_id           0
customer_id        0
order_date         0
order_status       0
payment_method    15
shipping_city     30
shipping_state     0
dtype: int64

In [27]:
orders.dropna(inplace=True)

In [28]:
orders.isnull().sum()

order_id          0
customer_id       0
order_date        0
order_status      0
payment_method    0
shipping_city     0
shipping_state    0
dtype: int64

In [29]:
orders.duplicated().sum()

np.int64(20)

In [30]:
orders.drop_duplicates(inplace=True)

In [31]:
orders.duplicated().sum()

np.int64(0)

In [32]:
orders['shipping_state'].unique()

<StringArray>
[  'West Bengal', 'Uttar Pradesh',     'Karnataka',     'Rajasthan',
        'Kerala',        'Punjab',         'Delhi',   'Maharashtra',
       'Gujarat',    'Tamil Nadu',     'Telangana',       'Haryana']
Length: 12, dtype: str

In [33]:
orders['shipping_city'].unique()

<StringArray>
[ 'Ludhiana',    'Mumbai', 'Ahmedabad',     'Delhi',    'Jaipur', 'Hyderabad',
     'Kochi',   'Kolkata',   'Lucknow', 'Bengaluru',   'Chennai',  'Gurugram']
Length: 12, dtype: str

In [34]:
orders['payment_method'].unique()

<StringArray>
['Net Banking', 'Debit Card', 'UPI', 'COD', 'Credit Card']
Length: 5, dtype: str

In [35]:
orders['order_status'].unique()

<StringArray>
['Delivered', 'Shipped', 'Returned', 'Cancelled']
Length: 4, dtype: str

In [36]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [37]:
orders.info()

<class 'pandas.DataFrame'>
Index: 9956 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9956 non-null   str
 1   customer_id     9956 non-null   int64
 2   order_date      9956 non-null   datetime64[us]
 3   order_status    9956 non-null   str
 4   payment_method  9956 non-null   str
 5   shipping_city   9956 non-null   str
 6   shipping_state  9956 non-null   str
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 622.2 KB

In [38]:
orders.head(8)

,order_id,customer_id,order_date,order_status,payment_method,shipping_city,shipping_state
0,O000001,11824,2024-05-27,Delivered,Net Banking,Ludhiana,West Bengal
1,O000002,12012,2024-12-07,Delivered,Debit Card,Mumbai,Uttar Pradesh
2,O000003,12000,2025-05-09,Delivered,UPI,Ahmedabad,Karnataka
3,O000004,10411,2024-01-23,Delivered,COD,Delhi,Rajasthan
4,O000005,12293,2024-04-14,Delivered,Debit Card,Jaipur,Kerala
5,O000006,10387,2025-11-05,Delivered,Net Banking,Ludhiana,Punjab
6,O000007,11749,2025-08-01,Delivered,UPI,Jaipur,Delhi
7,O000008,12406,2025-07-11,Shipped,UPI,Ahmedabad,West Bengal

## clean the payments table

In [39]:
payments = pd.read_csv("C:\\Users\\hp\\OneDrive\\Desktop\\amazone\\payments.csv")
payments.head(5)

   payment_id order_id payment_date payment_method payment_status
0  PAY0000001  O000001   2024-05-27    Net Banking           Paid
1  PAY0000002  O000002   2024-12-07     Debit Card           Paid
2  PAY0000003  O000003   2025-05-09            UPI           Paid
3  PAY0000004  O000004   2024-01-23            COD           Paid
4  PAY0000005  O000005   2024-04-14     Debit Card           Paid

In [40]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      10000 non-null  str
 1   order_id        10000 non-null  str
 2   payment_date    10000 non-null  str
 3   payment_method  10000 non-null  str
 4   payment_status  10000 non-null  str
dtypes: str(5)
memory usage: 390.8 KB

In [41]:
payments.isnull().sum()

payment_id        0
order_id          0
payment_date      0
payment_method    0
payment_status    0
dtype: int64

In [42]:
payments.duplicated().sum()

np.int64(0)

In [43]:
payments['payment_method'].unique()

<StringArray>
['Net Banking', 'Debit Card', 'UPI', 'COD', 'Credit Card']
Length: 5, dtype: str

In [44]:
payments['payment_status'].unique()

<StringArray>
['Paid', 'Refunded', 'Failed', 'Pending']
Length: 4, dtype: str

In [45]:
payments['payment_date'] = pd.to_datetime(payments['payment_date'])

In [46]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      10000 non-null  str
 1   order_id        10000 non-null  str
 2   payment_date    10000 non-null  datetime64[us]
 3   payment_method  10000 non-null  str
 4   payment_status  10000 non-null  str
dtypes: datetime64[us](1), str(4)
memory usage: 390.8 KB

In [47]:
payments.head(8)

   payment_id order_id payment_date payment_method payment_status
0  PAY0000001  O000001   2024-05-27    Net Banking           Paid
1  PAY0000002  O000002   2024-12-07     Debit Card           Paid
2  PAY0000003  O000003   2025-05-09            UPI           Paid
3  PAY0000004  O000004   2024-01-23            COD           Paid
4  PAY0000005  O000005   2024-04-14     Debit Card           Paid
5  PAY0000006  O000006   2025-11-05    Net Banking           Paid
6  PAY0000007  O000007   2025-08-01            UPI           Paid
7  PAY0000008  O000008   2025-07-11            UPI           Paid

## Clean the products table

In [48]:
products = pd.read_csv("C:\\Users\\hp\\OneDrive\\Desktop\\amazone\\products.csv")
products.head(5)

,product_id,product_name,category,brand,unit_price,supplier,stock_quantity
0,P0001,Dumbbells,Sports,FitPro,999999.99,Supplier_D,46
1,P0002,Smartwatch,Electronics,TechMax,46464.24,Supplier_B,281
2,P0003,Jeans,Clothing,TechMax,19021.82,Supplier_B,339
3,P0004,Lamp,Home,Zenix,23290.06,Supplier_A,361
4,P0005,Jeans,Clothing,UrbanStyle,4607.41,Supplier_D,91

In [49]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      300 non-null    str
 1   product_name    300 non-null    str
 2   category        300 non-null    str
 3   brand           285 non-null    str
 4   unit_price      300 non-null    float64
 5   supplier        300 non-null    str
 6   stock_quantity  300 non-null    int64
dtypes: float64(1), int64(1), str(5)
memory usage: 16.5 KB

In [50]:
products.isnull().sum()

product_id         0
product_name       0
category           0
brand             15
unit_price         0
supplier           0
stock_quantity     0
dtype: int64

In [51]:
products.dropna(inplace=True)

In [52]:
products.isnull().sum()

product_id        0
product_name      0
category          0
brand             0
unit_price        0
supplier          0
stock_quantity    0
dtype: int64

In [53]:
products.duplicated().sum()

np.int64(0)

In [54]:
products['category'].unique()

<StringArray>
['Sports', 'Electronics', 'Clothing', 'Home', 'Beauty', 'Books']
Length: 6, dtype: str

In [55]:
products['supplier'].unique()

<StringArray>
['Supplier_D', 'Supplier_B', 'Supplier_A', 'Supplier_C']
Length: 4, dtype: str

In [56]:
products['brand'].unique()

<StringArray>
['FitPro', 'TechMax', 'Zenix', 'UrbanStyle', 'Amazon Basics', 'Nova']
Length: 6, dtype: str

In [57]:
products.head(8)

,product_id,product_name,category,brand,unit_price,supplier,stock_quantity
0,P0001,Dumbbells,Sports,FitPro,999999.99,Supplier_D,46
1,P0002,Smartwatch,Electronics,TechMax,46464.24,Supplier_B,281
2,P0003,Jeans,Clothing,TechMax,19021.82,Supplier_B,339
3,P0004,Lamp,Home,Zenix,23290.06,Supplier_A,361
4,P0005,Jeans,Clothing,UrbanStyle,4607.41,Supplier_D,91
6,P0007,Football,Sports,Amazon Basics,14551.96,Supplier_B,211
7,P0008,T-Shirt,Clothing,UrbanStyle,8182.39,Supplier_C,74
8,P0009,Tablet,Electronics,Amazon Basics,27316.66,Supplier_C,377

## clean the returns tables

In [58]:
returns = pd.read_csv("C:\\Users\\hp\\OneDrive\\Desktop\\amazone\\returns.csv")
returns.head(5)

  return_id order_id  customer_id return_date  return_reason  refund_amount
0    R00001  O000018        11974  2025-04-03   Changed Mind        2585.23
1    R00002  O000023        10199  2024-02-04   Changed Mind       19034.06
2    R00003  O000059        12268  2024-05-24  Quality Issue       10740.29
3    R00004  O000076        11658  2025-10-01  Quality Issue       14616.30
4    R00005  O000090        12325  2025-04-16     Wrong Item        6541.85

In [59]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 723 entries, 0 to 722
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      723 non-null    str
 1   order_id       723 non-null    str
 2   customer_id    723 non-null    int64
 3   return_date    723 non-null    str
 4   return_reason  723 non-null    str
 5   refund_amount  723 non-null    float64
dtypes: float64(1), int64(1), str(4)
memory usage: 34.0 KB

In [60]:
returns.isnull().sum()

return_id        0
order_id         0
customer_id      0
return_date      0
return_reason    0
refund_amount    0
dtype: int64

In [61]:
returns.duplicated().sum()

np.int64(0)

In [62]:
returns['return_reason'].unique()

<StringArray>
['Changed Mind', 'Quality Issue', 'Wrong Item', 'Damaged', 'Late Delivery']
Length: 5, dtype: str

In [63]:
returns['return_date'] = pd.to_datetime(returns['return_date'])

In [64]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 723 entries, 0 to 722
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      723 non-null    str
 1   order_id       723 non-null    str
 2   customer_id    723 non-null    int64
 3   return_date    723 non-null    datetime64[us]
 4   return_reason  723 non-null    str
 5   refund_amount  723 non-null    float64
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 34.0 KB

In [65]:
returns.head(8)

  return_id order_id  customer_id return_date  return_reason  refund_amount
0    R00001  O000018        11974  2025-04-03   Changed Mind        2585.23
1    R00002  O000023        10199  2024-02-04   Changed Mind       19034.06
2    R00003  O000059        12268  2024-05-24  Quality Issue       10740.29
3    R00004  O000076        11658  2025-10-01  Quality Issue       14616.30
4    R00005  O000090        12325  2025-04-16     Wrong Item        6541.85
5    R00006  O000153        12226  2024-05-26     Wrong Item       28615.41
6    R00007  O000180        10596  2025-10-12     Wrong Item       19976.44
7    R00008  O000209        10038  2025-08-25        Damaged        6215.73

In [55]:
customers.to_csv('customers.csv',index=False)
order_items.to_csv('order_items.csv',index=False)
orders.to_csv('orders.csv',index=False)
payments.to_csv('payments.csv',index=False)
products.to_csv('products.csv',index=False)
returns.to_csv('returns.csv',index=False)